name = "MOPS"
uuid = "5952859f-f961-4eab-a85d-0fab7a00bdad"
authors = ["Bowen S. Zhu <bszhu@fas.harvard.edu>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Combinatorics = "1.0"
DocStringExtensions = "0.9"
SpecialFunctions = "2.1"
Symbolics = "4.13"
julia = "1.6"
